# Generated by Django 6.0.5 on 2026-05-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
