# Generated by Django 6.0.5 on 2026-05-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='daraz_url',
            field=models.URLField(blank=True, help_text='Direct Daraz product URL (optional). If blank, a search link is auto-generated.', max_length=600),
        ),
    ]
